################################################################################
GRUNT_APT_EXTRAS  = backports         # for Debian Stable backports
GRUNT_APT_EXTRAS += bitlbee-dev       # Bitlbee nightly builds
GRUNT_APT_EXTRAS += conkeror-nightly  # Conkeror nightly builds
GRUNT_APT_EXTRAS += emacs-snapshot    # Emacs nightly builds
GRUNT_APT_EXTRAS += mozilla           # Debian Mozilla team (Firefox)

################################################################################
GRUNT_HOME ?= ../grunt
include $(GRUNT_HOME)/debian/mk/apt.mk
